#
# lua Travis-CI Hook
#

# Travis language: c(sharp) :-P
language: c

# We need CMake, Mono and NUnit
install:
  - sudo apt-get install cmake mono-devel nunit >/dev/null 2>&1

script:
  - uname --all
  - git submodule update --init --recursive
  - ./run_all.linux.sh

# Execute additional tests or commands
#after_script:
#  - [run additional test commans]

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  irc:
    channels:
      - "irc.rizon.net#schumix2"
